{
 "title": "Heart 360 Global Dashboard",
 "time": { "from": "2023-10-01T00:00:00.000Z", "to": "2024-09-01T00:00:00.000Z" },
 "panels": [
  { "title": "Overview indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patients protected from heart attacks and strokes with world-class treatment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month, nb_patients_controlled from heart360_patients_catagory "
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * nb_patients_controlled / nb_patients_under_care as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY"
    }
   ]
  },
  {
   "title": "BP Uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * nb_patients_uncontrolled / nb_patients_under_care as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * nb_patients_no_visit / nb_patients_under_care as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY;"
    }
   ]
  }
 ]
}