{
 "title": "HEARTS360 Dashboard Per Facility (With Security)",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Facility",
    "query": "SELECT DISTINCT ou.name AS __text, ou.id::text AS __value FROM org_units ou WHERE ou.level = 3 AND EXISTS (SELECT 1 FROM patients p WHERE p.org_unit_id IN (SELECT id FROM get_descendant_ids(ou.id))) ORDER BY ou.name"
   },
   {
    "name": "isAllowed",
    "query": "\nSELECT \n    count(*) as is_allowed\nFROM \"user\" u\nleft outer join team_member tm on tm.user_id = u.id\nleft outer join team t on tm.team_id = t.id\nWHERE \n   u.id = ${__user.id} \n   AND \n     (t.name IN (\n        'heart360tk_facility_view_patients_' || trim ( lower ('${Facility}' )), \n        'heart360tk_facility_view_aggregated_' || trim ( lower ('${Facility}' )), \n        'heart360tk_facility_view_patients_ALL',\n        'heart360tk_facility_view_aggregated_ALL')\n     OR u.is_admin)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  display:flex;\n  gap:32px;\n  border-bottom:1px solid #e0e0e0;\n  margin-bottom:16px;\n  font-size:18px;\n\">\n\n  <span style=\"\n       padding:8px 0;\n       font-weight:600;\n       color:#000;\n       border-bottom:2px solid #3b82f6;\n     \">\n    Hypertension dashboard\n  </span>\n\n  <a target=\"_top\" href=\"/d/diabetes_dashboard_secure?orgId=1&var-Facility=${Facility}&${__url_time_range}\"\n     style=\"\n       padding:8px 0;\n       text-decoration:none;\n       color:#555;\n     \">\n    Diabetes dashboard\n  </a>\n\n  <a target=\"_top\" href=\"/d/heart360-overdue-secure?orgId=1&var-Facility=${Facility}&${__url_time_range}\"\n     style=\"\n       padding:8px 0;\n       text-decoration:none;\n       color:#555;\n     \">\n    Overdue patients list\n  </a>\n\n</div>"
   }
  },
  { "title": "Overview indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Patients protected from heart attacks and strokes with world-class treatment",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select\n  ref_month,\n  sum(nb_patients_controlled) nb_patients_controlled\nfrom heart360_patients_catagory\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) and $isAllowed  >0 \ngroup by 1"
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_controlled) / (0.00000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) and $isAllowed  >0 \ngroup by 1"
    }
   ]
  },
  {
   "title": "BP uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month,\n    sum(100.00 * nb_patients_uncontrolled) / (0.00000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as uncontrolled_pct\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) and $isAllowed > 0\ngroup by 1"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 14 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_no_visit) / (0.00000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_3M_INCL_VISITS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) and $isAllowed  >0 \ngroup by 1"
    }
   ]
  },
  {
   "title": "Patients under care",
   "type": "timeseries",
   "description": "Patients with hypertension with at least 1 visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "SELECT\n  uc.ref_month,\n  SUM(uc.cumulative_number_of_patients) AS cumulative_number_of_patients,\n  SUM(uc.nb_patients_under_care) AS nb_patients_under_care,\n  SUM(cat.nb_patients_newly_registered) AS nb_new_patients\nFROM HEART360_PATIENTS_UNDER_CARE uc\nLEFT JOIN HEART360_PATIENTS_CATAGORY cat ON uc.ref_month = cat.ref_month AND uc.org_unit_id = cat.org_unit_id\nWHERE uc.org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) AND $isAllowed > 0\nGROUP BY uc.ref_month\nORDER BY uc.ref_month;"
    }
   ]
  },
  {
   "title": "12 month lost to follow-up",
   "type": "timeseries",
   "description": "Patients with hypertension with no visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 22 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n  heart360_patients_under_care.ref_month,\n  (100.0 * sum(COALESCE(heart360_patients_under_care.nb_patients_lost_to_follow_up, 0))) / \n  NULLIF(sum(heart360_patients_under_care.cumulative_number_of_patients), 0) as lost_to_follow_up_pct\nfrom heart360_patients_under_care\nwhere heart360_patients_under_care.org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) and $isAllowed > 0\ngroup by 1"
    }
   ]
  },
  { "title": "Overdue patients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Overdue patients",
   "type": "timeseries",
   "description": "Patients that are overdue at the start of the month",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "SELECT\n  ref_month AS \"time\",\n  SUM(overdue_on_first) AS overdue_on_first\nFROM HEART360_OVERDUE_START_OF_MONTH\nWHERE org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) AND $isAllowed > 0\nGROUP BY ref_month\nORDER BY ref_month;"
    }
   ]
  },
  {
   "title": "Overdue patients called",
   "type": "timeseries",
   "description": "Patients called during the month.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "SELECT\n  ref_month AS \"time\",\n  overdue_patients_called\nFROM HEART360_OVERDUE_PATIENTS_CALLED\nWHERE org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) AND $isAllowed > 0\nORDER BY ref_month;"
    }
   ]
  },
  {
   "title": "Overdue patients that returned to care",
   "type": "timeseries",
   "description": "Patients called during the month.",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 31 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "SELECT\n  ref_month AS \"time\",\n  overdue_returned_to_care\nFROM HEART360_OVERDUE_RETURNED_TO_CARE\nWHERE org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) AND $isAllowed > 0\nORDER BY ref_month;"
    }
   ]
  },
  { "title": "Cohort", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Cohort Report",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "heart360tk_database",
     "rawSql": "SELECT\n  TO_CHAR(registration_quarter, 'Mon') || ' - ' ||\n  TO_CHAR(registration_quarter + interval '2 month', 'Mon YYYY')\n  AS quarter_label,\n\n  SUM(CASE WHEN status_at_end_of_interval = 'controlled' THEN 1 END)\n  AS \"% Controlled BP at latest visit in following quarter\",\n\n  SUM(CASE WHEN status_at_end_of_interval = 'uncontrolled' THEN 1 END)\n  AS \"% Uncontrolled BP at latest visit in following quarter\",\n\n  SUM(CASE WHEN status_at_end_of_interval = 'missed visit' THEN 1 END)\n  AS \"% Patients with no visit in following quarter\"\n\nFROM HEART360_COHORT_PATIENT_DETAILS\nWHERE $__timeFilter(registration_quarter)\n  AND org_unit_id IN (SELECT id FROM get_descendant_ids($Facility::int)) AND $isAllowed > 0\nGROUP BY registration_quarter\nORDER BY registration_quarter;"
    }
   ]
  }
 ]
}