{
 "title": "HEARTS360 Region Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "reference_month",
    "query": "(select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))"
   }
  ]
 },
 "panels": [
  { "title": "Overview indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patients protected from heart attacks and strokes with world-class treatment",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select\n  ref_month,\n  sum(nb_patients_controlled) nb_patients_controlled\nfrom heart360_patients_catagory\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1"
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * sum(nb_patients_controlled) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1"
    }
   ]
  },
  {
   "title": "BP uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month,\n    100.00 * sum(nb_patients_uncontrolled) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as uncontrolled_pct\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * sum(nb_patients_no_visit) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1"
    }
   ]
  },
  {
   "title": "Patients under care",
   "type": "timeseries",
   "description": "Patients with hypertension with at least 1 visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    HEART360_PATIENTS_CATAGORY.ref_month,\n    sum(cumulative_number_of_patients) cumulative_number_of_patients,\n    sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS) as nb_patients_under_care,\n    sum(nb_new_patients) nb_new_patients\nfrom HEART360_PATIENTS_CATAGORY\nleft outer join heart360_patients_registered\n    on HEART360_PATIENTS_CATAGORY.ref_month = heart360_patients_registered.ref_month \n    and HEART360_PATIENTS_CATAGORY.org_unit_id = heart360_patients_registered.org_unit_id\nwhere HEART360_PATIENTS_CATAGORY.org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "12 month lost to follow-up",
   "type": "timeseries",
   "description": "Patients with hypertension with no visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 20 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n  heart360_patients_under_care.ref_month,\n  (100.0 * sum(COALESCE(heart360_patients_under_care.nb_patients_lost_to_follow_up, 0))) / \n  NULLIF(sum(heart360_patients_under_care.cumulative_number_of_patients), 0) as lost_to_follow_up_pct\nfrom heart360_patients_under_care\nwhere heart360_patients_under_care.org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\ngroup by 1"
    }
   ]
  },
  { "title": "District Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "Treatment outcomes for patients with hypertension at their latest visit before <u>**${reference_month:date:MMMM YYYY}**</u>"
   }
  },
  {
   "title": "Facility Details by District",
   "type": "volkovlabs-table-panel",
   "description": "$user",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "SELECT\n    HEART360_PATIENTS_CATAGORY.ref_month,\n    child_ou.id as child_id,\n    child_ou.name as child_name,\n    SUM(nb_patients_under_care) AS nb_patients_under_care,\n    SUM(COALESCE(nb_new_patients, 0)) AS nb_patients_newly_registered,\n    SUM(nb_patients_controlled) AS nb_patients_controlled,\n    ROUND(100.0 * SUM(nb_patients_controlled) / NULLIF(SUM(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS), 0)) AS per_patients_controlled,\n    SUM(nb_patients_uncontrolled) AS nb_patients_uncontrolled,\n    ROUND(100.0 * SUM(nb_patients_uncontrolled) / NULLIF(SUM(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS), 0)) AS per_patients_uncontrolled,\n    SUM(nb_patients_no_visit) AS nb_patients_no_visit,\n    ROUND(100.0 * SUM(nb_patients_no_visit) / NULLIF(SUM(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS), 0)) AS per_patients_no_visit\nFROM HEART360_PATIENTS_CATAGORY\nJOIN org_unit_lineage lin ON HEART360_PATIENTS_CATAGORY.org_unit_id = lin.org_unit_id\nJOIN org_units child_ou ON lin.ancestor_id = child_ou.id AND child_ou.parent_id = $Region::int\nLEFT JOIN heart360_patients_registered\n    ON HEART360_PATIENTS_CATAGORY.ref_month = heart360_patients_registered.ref_month\n    AND HEART360_PATIENTS_CATAGORY.org_unit_id = heart360_patients_registered.org_unit_id\nWHERE HEART360_PATIENTS_CATAGORY.ref_month = (\n    SELECT MAX(ref_month) FROM HEART360_PATIENTS_CATAGORY\n    WHERE org_unit_id IN (SELECT id FROM get_descendant_ids($Region::int))\n    AND $__timeFilter(ref_month)\n)\nGROUP BY HEART360_PATIENTS_CATAGORY.ref_month, child_ou.id, child_ou.name\nORDER BY child_ou.name;"
    }
   ]
  }
 ]
}