{
 "title": "HEARTS360 Dashboard Per Facility",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Facility",
    "query": "select distinct facility from patients"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  display:flex;\n  gap:32px;\n  border-bottom:1px solid #e0e0e0;\n  margin-bottom:16px;\n  font-size:18px;\n\">\n\n  <span style=\"\n       padding:8px 0;\n       font-weight:600;\n       color:#000;\n       border-bottom:2px solid #3b82f6;\n     \">\n    Hypertension dashboard\n  </span>\n\n  <a href=\"/d/heart360_facility_overdue_patients/heart-360-overdue-patients-by-facility\n?orgId=1\n&from=now-1y\n&to=now\n&timezone=browser\n&var-facility=${Facility}\"\n     style=\"\n       padding:8px 0;\n       text-decoration:none;\n       color:#555;\n     \">\n    Overdue patients list\n  </a>\n\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: right;\">\n  \n  <a href=\"/d/heart360demo/heart-360-global-dashboard?orgId=1&from=now-1y&to=now&timezone=browser\" style=\" \n        background-color: #f5f5f5;\n        color: #333333; \n        border: 1px solid #d0d0d0;\n        padding: 4.5px 20px; \n        font-size: 18px; \n        font-weight: 600; \n        border-radius: 6px; \n        text-decoration: none; \n        display: inline-block; \n        font-family: Inter, Helvetica, Arial, sans-serif;\n        transition: background-color 0.2s;\n  \">\n    District Dashboard\n  </a>\n\n  <a href=\"http://localhost:8080/\" target=\"_blank\" style=\"\n    background-color: #3274d9; \n    color: white; \n    padding: 6px 40px; \n    font-size: 18px; \n    font-weight: 600; \n    border-radius: 6px; \n    text-decoration: none; \n    display: inline-block; \n    font-family: Inter, Helvetica, Arial, sans-serif;\n    box-shadow: 0 2px 0 rgba(0,0,0,0.1);\n    transition: background-color 0.2s;\n  \">\n    Upload File\n  </a>\n\n</div>"
   }
  },
  {
   "title": "Overview indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Patients protected from heart attacks and strokes with world-class treatment",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "metrics_db",
       "rawSql": "select\n  ref_month,\n  sum(nb_patients_controlled) nb_patients_controlled\nfrom heart360_patients_catagory\nwhere facility = '$Facility'\ngroup by 1"
      }
     ]
    },
    {
     "title": "Hypertension treatment cascade",
     "type": "barchart",
     "description": "Estimated population with hypertension is derived from Community Survey.\n\nPatients under care are patients with hypertension with at least 1 visit in the past 12 months.",
     "gridPos": { "h": 10, "w": 7, "x": 16, "y": 2 },
     "targets": [
      {
       "dataset": "metrics_db",
       "rawSql": "select \n  heart360_patients_registered.ref_month,\n  100.0 as estimated_people_with_hypertension_pct,\n  (sum(cumulative_number_of_patients)::numeric / 5600.0 * 100.0) as registered_pct_of_estimated,\n  (sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)::numeric / 5600.0 * 100.0) as under_care_pct_of_estimated,\n  (sum(nb_patients_controlled)::numeric / 5600.0 * 100.0) as controlled_pct_of_estimated\nfrom heart360_patients_catagory\njoin heart360_patients_registered on heart360_patients_registered.ref_month = heart360_patients_catagory.ref_month and heart360_patients_catagory.facility= heart360_patients_registered.facility\nwhere heart360_patients_catagory.ref_month=(select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))\n  and heart360_patients_catagory.facility='$Facility'\ngroup by 1"
      }
     ]
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_controlled) / (0.00000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere facility = '$Facility'\ngroup by 1"
    }
   ]
  },
  {
   "title": "BP uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month,\n    sum(100.00 * nb_patients_uncontrolled) / (sum(000000001 + NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as uncontrolled_pct\nfrom HEART360_PATIENTS_CATAGORY\nwhere facility = '$Facility'\ngroup by 1"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 4 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_no_visit) / (0.00000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\nwhere facility = '$Facility'\ngroup by 1"
    }
   ]
  },
  {
   "title": "Patients under care",
   "type": "timeseries",
   "description": "Patients with hypertension with at least 1 visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    HEART360_PATIENTS_CATAGORY.ref_month,\n    sum(cumulative_number_of_patients) cumulative_number_of_patients,\n    sum(nb_patients_under_care) as nb_patients_under_care,\n    sum(nb_new_patients) nb_new_patients\nfrom HEART360_PATIENTS_CATAGORY\nleft outer join heart360_patients_registered on HEART360_PATIENTS_CATAGORY.ref_month = heart360_patients_registered.ref_month\n and  HEART360_PATIENTS_CATAGORY.facility = heart360_patients_registered.facility\nwhere HEART360_PATIENTS_CATAGORY.facility = '$Facility'\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "12 month lost to follow-up",
   "type": "timeseries",
   "description": "Patients with hypertension with no visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n  heart360_patients_under_care.ref_month,\n  (100.0 * sum(COALESCE(heart360_patients_under_care.nb_patients_lost_to_follow_up, 0))) / \n  NULLIF(sum(heart360_patients_under_care.cumulative_number_of_patients), 0) as lost_to_follow_up_pct\nfrom heart360_patients_under_care\nwhere heart360_patients_under_care.facility = '$Facility'\ngroup by 1"
    }
   ]
  },
  { "title": "Cohort", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cohort Report",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "heart360tk_database",
     "rawSql": "select \n    registration_quarter,\n    sum(case when status_at_end_of_interval ='missed visit' then 1 end) as nb_missed_visit,\n    sum(case when status_at_end_of_interval ='uncontrolled' then 1 end) as nb_uncontrolled,\n    sum(case when status_at_end_of_interval ='controlled' then 1 end) as nb_controlled\nfrom HEART360_COHORT_PATIENT_DETAILS\nwhere facility ='$Facility'\ngroup by registration_quarter;"
    }
   ]
  }
 ]
}