{
 "title": "Heart 360 Global Dashboard",
 "time": { "from": "2023-10-01T00:00:00.000Z", "to": "2024-09-01T00:00:00.000Z" },
 "panels": [
  { "title": "Overview indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patients protected from heart attacks and strokes with world-class treatment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select\n  ref_month,\n  sum(nb_patients_controlled) nb_patients_controlled\nfrom heart360_patients_catagory\ngroup by 1"
    }
   ]
  },
  {
   "title": "Cascade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n  heart360_patients_registered.ref_month,\n  sum(cumulative_number_of_patients) as cumulative_number_of_patients,\n  sum(nb_patients_under_care) as nb_patients_under_care,\n  sum(nb_patients_controlled) as nb_patients_controlled\nfrom public.heart360_patients_catagory\njoin public.heart360_patients_registered on heart360_patients_registered.ref_month = heart360_patients_catagory.ref_month\nwhere heart360_patients_catagory.ref_month=(select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))\ngroup by 1\n\n\n\n"
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_controlled / nb_patients_under_care) as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "BP Uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_uncontrolled / nb_patients_under_care) as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    sum(100.00 * nb_patients_no_visit / nb_patients_under_care) as Control_rate\nfrom public.HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "Patients under care",
   "type": "timeseries",
   "description": "Patients with hypertension with at least 1 visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    public.HEART360_PATIENTS_CATAGORY.ref_month,\n    sum(cumulative_number_of_patients) cumulative_number_of_patients,\n    sum(nb_patients_under_care * 0.9) as nb_patients_under_care,\n    sum(nb_new_patients) nb_new_patients\nfrom public.HEART360_PATIENTS_CATAGORY\nleft outer join public.heart360_patients_registered on public.HEART360_PATIENTS_CATAGORY.ref_month = public.heart360_patients_registered.ref_month\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "12 month lost to follow-up",
   "type": "timeseries",
   "description": "Patients with hypertension with no visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month, sum(COALESCE(nb_patients_lost_to_follow_up, 0)) nb_patients_lost_to_follow_up\nfrom public.heart360_patients_under_care\ngroup by 1"
    }
   ]
  },
  {
   "title": "Opportunistic screening",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 18 },
   "options": {
    "content": "No Data for opportunistic Screeing"
   }
  }
 ]
}