{
 "title": "HEARTS360 Global Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "reference_month",
    "query": "(select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Patients protected from heart attacks and strokes with world-class treatment",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "metrics_db",
       "rawSql": "select\n  ref_month,\n  sum(nb_patients_controlled) nb_patients_controlled\nfrom heart360_patients_catagory\ngroup by 1"
      }
     ]
    },
    {
     "title": "Hypertension treatment cascade",
     "type": "barchart",
     "description": "Estimated population with hypertension is derived from Community Survey.\n\nPatients under care are patients with hypertension with at least 1 visit in the past 12 months.",
     "gridPos": { "h": 10, "w": 7, "x": 16, "y": 1 },
     "targets": [
      {
       "dataset": "metrics_db",
       "rawSql": "select \n  heart360_patients_registered.ref_month,\n  100.0 as estimated_people_with_hypertension_pct,\n  (sum(cumulative_number_of_patients)::numeric / 8000.0 * 100.0) as registered_pct_of_estimated,\n  (sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)::numeric / 8000.0 * 100.0) as under_care_pct_of_estimated,\n  (sum(nb_patients_controlled)::numeric / 8000.0 * 100.0) as controlled_pct_of_estimated\nfrom heart360_patients_catagory\njoin heart360_patients_registered on heart360_patients_registered.ref_month = heart360_patients_catagory.ref_month and heart360_patients_catagory.facility= heart360_patients_registered.facility\nwhere heart360_patients_catagory.ref_month=(select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))\ngroup by 1"
      }
     ]
    }
   ]
  },
  { "title": "Program management indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "BP controlled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * sum(nb_patients_controlled) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "BP uncontrolled at latest visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select ref_month,\n    100.00 * sum(nb_patients_uncontrolled) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as uncontrolled_pct\nfrom HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "No visit in past 3 months",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 2 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    ref_month,\n    100.00 * sum(nb_patients_no_visit) / (0.000001 + sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS)) as Control_rate\nfrom HEART360_PATIENTS_CATAGORY\ngroup by 1"
    }
   ]
  },
  {
   "title": "Patients under care",
   "type": "timeseries",
   "description": "Patients with hypertension with at least 1 visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n    HEART360_PATIENTS_CATAGORY.ref_month,\n    sum(cumulative_number_of_patients) cumulative_number_of_patients,\n    sum(NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS) as nb_patients_under_care,\n    sum(nb_new_patients) nb_new_patients\nfrom HEART360_PATIENTS_CATAGORY\nleft outer join heart360_patients_registered\n    on HEART360_PATIENTS_CATAGORY.ref_month = heart360_patients_registered.ref_month \n    and HEART360_PATIENTS_CATAGORY.facility=heart360_patients_registered.facility\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "12 month lost to follow-up",
   "type": "timeseries",
   "description": "Patients with hypertension with no visit in the past 12 months\n\n",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 10 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "select \n  heart360_patients_under_care.ref_month,\n  (100.0 * sum(COALESCE(heart360_patients_under_care.nb_patients_lost_to_follow_up, 0))) / \n  NULLIF(sum(heart360_patients_under_care.cumulative_number_of_patients), 0) as lost_to_follow_up_pct\nfrom heart360_patients_under_care\ngroup by 1"
    }
   ]
  },
  { "title": "Cohort", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cohort Report",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "heart360tk_database",
     "rawSql": "select \n    registration_quarter,\n    sum(case when status_at_end_of_interval ='missed visit' then 1 end) as nb_missed_visit,\n    sum(case when status_at_end_of_interval ='uncontrolled' then 1 end) as nb_uncontrolled,\n    sum(case when status_at_end_of_interval ='controlled' then 1 end) as nb_controlled\nfrom HEART360_COHORT_PATIENT_DETAILS\ngroup by registration_quarter;"
    }
   ]
  },
  { "title": "Facility Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "Treatment outcomes for patients with hypertension at their latest visit before <u>**${reference_month:date:MMMM YYYY}**</u>"
   }
  },
  {
   "type": "volkovlabs-table-panel",
   "description": "$user",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "metrics_db",
     "rawSql": "\nselect\n    ref_month,\n    facility,\n    nb_patients_under_care,\n    nb_patients_newly_registered,\n    nb_patients_controlled,\n    (100 * nb_patients_controlled) / (0000001 + NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS) as per_patients_controlled,\n    nb_patients_uncontrolled,\n    (100* nb_patients_uncontrolled) / (0000001 + NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS) as per_patients_uncontrolled,\n    nb_patients_no_visit,\n    (100* nb_patients_no_visit) / (0000001 + NB_PATIENTS_UNDER_CARE_REGISTERED_BEFORE_THE_PAST_3_MONTHS) as per_patients_no_visit\nfrom heart360_patients_catagory\nwhere ref_month= (select max(ref_month) from heart360_patients_catagory where $__timeFilter(ref_month))\n;\n"
    }
   ]
  }
 ]
}